
oneflow-skin    : "aqua" 

locale                   : "en-US"
title                    : "OneFlow Jekyll Theme"
title_separator          : "-"
subtitle                 : " " 
url                      : "https://adrianac13.github.io/jamstack/" 
baseurl                  : 
repository               : "perstarke-webdev/oneflow-jekyll-theme" 
teaser                   : 
logo                     : "/assets/images/logo.webp" 
show-popup               : true 
                                
masthead_title           : " "  
sticky-masthead          : true 
                                
masthead-opacity         : 0.85 
                                
background-image         : 
background-image-mobile  : 
background-image-overlay : rgba(255, 255, 255, 0.5) 

footer:
  links: 
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
    - label: "X/Twitter"
      icon: "fab fa-x-twitter"
    - label: "Facebook"
      icon: "fab fa-facebook"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/"
    - label: "Dev"
      icon: "fab fa-dev"
      url: "https://dev.to/per-starke-642"
  copyright: "&#169 2025" 
  creator: 
      name: "Adrian Angeles"

include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed 

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

